# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvideostats',
            name='video_like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
