# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_song_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_url',
        ),
        migrations.AddField(
            model_name='song',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
