# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20190516_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcomment',
            name='moods',
        ),
    ]
