# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20190501_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
