# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='recommendation_five_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='recommendation_four_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='recommendation_one_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='recommendation_three_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='recommendation_two_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
