# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20190506_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='recommendation_five_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='recommendation_four_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='recommendation_one_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='recommendation_three_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='recommendation_two_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
