# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20190516_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newvideo',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='newvideo',
            name='updated',
        ),
    ]
