# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20190516_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvideo',
            name='video_title',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
