# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 16:27
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('songs', '0006_auto_20190506_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
