# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_song_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='api_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag_songs', to='songs.Song'),
        ),
    ]
