# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_song_api_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='api_tags',
        ),
    ]
