# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20190516_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVideoCorrectMood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, max_length=11, null=True)),
                ('video_title', models.TextField(blank=True, null=True)),
                ('correct_moods', models.CharField(choices=[('HAPPY', 'Happy'), ('IN-LOVE', 'In-Love'), ('SAD', 'Sad'), ('CONFIDENT-SASSY', 'Confident-sassy'), ('CHILL', 'Chill'), ('ANGRY', 'Angry')], default='UNKNOWN', max_length=20)),
            ],
        ),
    ]
