# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_remove_song_api_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='api_tags',
            field=models.ManyToManyField(to='songs.Tag'),
        ),
    ]
