# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_auto_20190508_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, max_length=11, null=True)),
                ('video_title', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
